### ISSUE TITLE
v0.6.0 release breaks Tour of Heroes tutorial

### ISSUE THREAD

**Issue by mathuin** [angular/in-memory-web-api#189]
I apologize if I missed something along the ways as this is my first venture into JavaScript let alone AngularJS.

I am following along with the [Angular Tour of Heroes tutorial](https://angular.io/tutorial/toh-pt6), and installed this package as per the instructions:
```
npm install angular-in-memory-web-api --save
```

All my calls to getHeroes() returned no data and the error text was `undefined`.

When I changed my `package.json` to reference `^0.5.4` instead of `^0.6.0`, everything worked as expected.  I looked at the release for `v0.6.0` and it appears to be for Angular 6 while I am using Angular 5.  I suspect that because the release was only three days ago that most folks will not have hit this issue.

While this release appears to have broken the tutorial, I do not believe it is this package's fault.  That being said, someone needs to fix something. :-)  If this issue belongs somewhere else, please let me know and I will file it there.  Thanks!

**Comment by zyzof** [comment]
I've just run into this too. Seems like the tutorial should state which version of angular-in-memory-web-api should be installed based on the installed version of Angular / rxjs.

You could try raising the issue over on the [Angular repo](https://github.com/angular/angular) to get [this part](https://github.com/angular/angular/blob/master/aio/content/tutorial/toh-pt6.md) of the documentation updated.

**Comment by healyje** [comment]
Same here...

**Comment by iHearty** [comment]
see #190

**Comment by devnido** [comment]
i had same problem in hero tutorial,  but i have installed version 0.5.0 and it works 
`npm install angular-in-memory-web-api@0.5.0 `

**Comment by healyje** [comment]
Yes, that works but doesn't address the problem.

**Comment by CMiksche** [comment]
The 0.5.0 version doesn't works with the Angular CLI 1.7.3 and Compiler CLI 5.2.0 - but the 0.5.4 version does ...

`npm install angular-in-memory-web-api@0.5.4 --save`

**Comment by jeffski13** [comment]
I should have checked this sooner! 
With the **v0.6.0** I get a **500 error**, "object (...) is not a function".

modify package.json to 
**"angular-in-memory-web-api": "~0.5.0",** 
and npm install to fix for now

Does anyone know how we can temporarily fix the heroes tutorial?
https://angular.io/tutorial/toh-pt6#enable-http-services 

NOTE: the above command results in 0.5.4 being installed, which works!

**Comment by ramesh-yadav** [comment]
it works fine with 0.5.3

**Comment by healyje** [comment]
We know it works with 0.5.4, does anyone know why it doesn't work with 0.6.0?

**Comment by mathuin** [comment]
@healyje I believe it does not work because there were significant changes between Angular v5 and Angular v6, and that some of those changes impacted this API, and that the API got updated before the parts of Angular used in the tutorial.

**Comment by Shivashankarn26** [comment]
I am new to angular and started with _Tour of Heroes_ tutorial. Now I am facing same issue with angular 6 version. I am using all the packages with updated version and still **"angular-in-memory-web-api"** is not working for 0.6.0 , I can't use 0.5.4 since my CLI and Angular are v6.

Any work around to continue with tutorial?

**Comment by aaronkelly111** [comment]
This is really bad form guys, this is the first impression of Angular, you´ve known about it for months and haven´t fixed the problem. First time users of Angular (me) hit this straight away.

**Comment by GeorgeOGorman** [comment]
I ran into this issue trying to learn Angular with the TOH tutorial. I couldn't get npm install angular-in-memory-web-api --save to work. Should I try to update the dependency packages with patch 6.0.5? Could somebody give a link to this?

**Comment by richie50** [comment]
I'm running into the same issue with Angular version 5.2.11 on CLI 1.7.4
